#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../projects/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: ws

depend: ws-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.ws $(@)

.PHONY: ws
ws:
	@$(MAKE) -f Makefile.ws all

.PHONY: ws-depend
ws-depend:
	@$(MAKE) -f Makefile.ws depend

project_name_list:
	@echo ws
